# Generated by Django 3.2.12 on 2022-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commentaire', models.DateTimeField(verbose_name='Date de debut du commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_droit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=30)),
                ('prenom_utilisateur', models.CharField(max_length=30)),
                ('login_utilisateur', models.CharField(max_length=30)),
                ('mot_de_passe_utilisateur', models.CharField(max_length=100)),
                ('ville_utilisateur', models.CharField(max_length=50)),
                ('tel_utilisateur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_annonce', models.CharField(max_length=50)),
                ('date_crea_annonce', models.DateTimeField(verbose_name="Date de debut d'annonce")),
                ('categorie', models.ManyToManyField(blank=True, to='AceDev.Categorie')),
            ],
        ),
    ]
