# Generated by Django 3.2.12 on 2022-05-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceDev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='contenu_annonce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
